### ISSUE TITLE
Test handling of options

### ISSUE THREAD

**Issue by jankatins** [jupyter/jupyter_kernel_test#20]
E.g. for the R kernel:

removing the svg option in the display mimetypes should result in an returned plot message without svg content:

```
old = getOption("jupyter.plot_mimetypes")
options(jupyter.plot_mimetypes = old[1:length(old)-1]) # svg is last
```

**Comment by takluyver** [comment]
I don't think this makes sense as part of the generic test suite - it's too kernel specific. However, since kernels use JKT by subclassing, we can easily add extra tests for specific kernels in the subclass - just define extra methods, e.g. `test_irkernel_plot_mimetypes`.
