### ISSUE TITLE
Pypi version out-of-date

### ISSUE THREAD

**Issue by jrshust** [jupyter/jupyter_kernel_test#23]
Whenever I pip install this package (pip or pip3) I am getting some ancient version instead of the new hotness. My build on IRkernel seems to be having this problem as well.

Specifically I want the execute_helper that now allows me to specify store_history and silent attributes. The out-of-date version is causing my PR on IRkernel to fail all the test cases :(.

Please advise on how to get the latest up there.

**Comment by takluyver** [comment]
I'd guess that you have a very old version of pip (<1.4, I think) which can't handle wheels. Upgrade pip, and then you should find the latest version:

```
pip install --upgrade setuptools pip
```

**Comment by takluyver** [comment]
Actually, no, I think I just need to upload a new release to PyPI. Sorry, I replied without checking the situation.

**Comment by jrshust** [comment]
Awesome, would love to benefit from the latest commits. If you could publish the latest that would be great! IRkernel tests would certainly appreciate it.

**Comment by takluyver** [comment]
I meant to do this last night, but I forgot. I'm away from my computer now,
so I won't be able to do it until tomorrow evening.

**Comment by takluyver** [comment]
A new version is now on PyPI.
