### ISSUE TITLE
'payload' attribute of 'execute_reply' message is optional according to the spec

### ISSUE THREAD

**Issue by AlexTugarev** [jupyter/jupyter_kernel_test#24]
We had to add an empty 'payload' to 'execute_reply' messages to make use of jupyter_kernel_test, but according the messaging spec it should be optional. Actually I'm not sure which one is right. 

cf. https://github.com/jupyter/jupyter_client/blob/master/docs/messaging.rst#execution-results

**Comment by takluyver** [comment]
@minrk should payload still be optional now that they're not-so-imminently deprecated? It seems more consistent that it always be there, even if it's an empty list.

**Comment by minrk** [comment]
Since the spec says they are optional, I'd let them be optional in the test, and only check that they are the right type if/when present. Both JupyterLab and current notebook appear to handle undefined payloads.

**Comment by blink1073** [comment]
Fixed in https://github.com/jupyter/jupyter_kernel_test/pull/58
