### ISSUE TITLE
Clarify that one cannot do `from jupyter_kernel_tests import KernelTests`

### ISSUE THREAD

**Issue by anntzer** [jupyter/jupyter_kernel_test#30]
If one starts with
```
from jupyter_kernel_tests import KernelTests

class MyTests(KernelTests):
    ....
```
(instead of importing the module and using a qualified name for the class)

then running the tests will try to run both the `MyTests` class *and* the `KernelTests` class, and the later will error.  A comment explaining this in the example test suites would save some head-scratching.

**Comment by takluyver** [comment]
Good point. Do you have time to do a PR?

**Comment by anntzer** [comment]
Nah, you get to do it :)
