### ISSUE TITLE
JupyterHub R Kernel Test does not work

### ISSUE THREAD

**Issue by korniichuk** [jupyter/jupyter_kernel_test#36]
Hi all,

[test_irkernel.py](https://github.com/jupyter/jupyter_kernel_test/blob/00e3f8fc1139757b1d7b52a8d0b3ff85da74b058/test_irkernel.py) does not work. R Kernel works correct. `test_execute_result` does not work. Looks like test waiting on "[1] 6" result and get just "6". Any ideas how I can fix `test_execute_result` in fastest way?

```
[korniichuk@jupyter ~]$ python3 test_ipykernel.py
/usr/lib/python3.6/site-packages/jupyter_client/manager.py:77: DeprecationWarning: KernelManager._kernel_name_changed is deprecated in traitlets 4.1: use @observe and @unobserve instead.
  def _kernel_name_changed(self, name, old, new):
s...s.ssss..s
======================================================================
FAIL: test_execute_result (__main__.IRKernelTests) (code='1+2+3')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/jupyter_kernel_test/__init__.py", line 216, in test_execute_result
    self.assertEqual(output_msgs[0]['msg_type'], 'execute_result')
AssertionError: 'display_data' != 'execute_result'
- display_data
+ execute_result
```
**Environment:**
CentOS 7.4
Linux jupyter 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Python 3.6.3
R 3.4.1
jupyter (1.0.0)
jupyter-client (5.1.0)
jupyter-console (5.2.0)
jupyter-core (4.3.0)
jupyter-kernel-gateway (2.0.1)
jupyter-kernel-test (0.3)
jupyterhub (0.8.0)

**Comment by takluyver** [comment]
I think IRkernel changed since the example in this repo was written. IRkernel has similar tests using JKT, but it doesn't have a `test_execute_result` now:

https://github.com/IRkernel/IRkernel/blob/master/tests/testthat/test_ir.py

**Comment by korniichuk** [comment]
@takluyver thank you very much for your extra fast answer and proposed link.
I'll test [test_ir.py](https://github.com/IRkernel/IRkernel/blob/master/tests/testthat/test_ir.py) solution. Have a nice day.
