### ISSUE TITLE
Parent header does not match expected

### ISSUE THREAD

**Issue by snmhas** [jupyter/jupyter_kernel_test#43]
Hi all,
I don't have enough knowledge about test code in Jupyterlab. I am trying to developed test code for my custom kernel.  I am getting bellow error when I ran test code using python3. 

Error :
File ".../jupyter_kernel_test/jupyter_kernel_test/msgspec_v5.py", line 121, in validate_message
    raise ValidationError("Parent header does not match expected")
jsonschema.exceptions.ValidationError: Parent header does not match expected.

Test Code : 
    def test_mykernel(self):
        reply, output_msgs = self.execute_helper(code='version()')
        self.assertEqual(output_msgs[0]['msg_type'], 'execute_result')
        self.assertEqual(output_msgs[0]['content']['name'], 'stdout')
        self.assertEqual(output_msgs[0]['content']['text'], 'v0.4.7')

Jupyterlab result : 
![capture](https://user-images.githubusercontent.com/40165026/43389574-56f3c6f2-93ec-11e8-8c62-6687712cce0c.PNG)

**Comment by blink1073** [comment]
Hi @snmhas, we've relaxed the parent header requirement for non-`reply`, messages in #62
