### ISSUE TITLE
Assertion on number of returned messages

### ISSUE THREAD

**Issue by pprzetacznik** [jupyter/jupyter_kernel_test#5]
During some tests I found out that in `jupyter_kernel_test` code there is an assertion on number of messages received from kernel after sending simple `hello world` request. Line 88: https://github.com/jupyter/jupyter_kernel_test/blob/master/jupyter_kernel_test/__init__.py#L88

There is set of programming languages (eg. Erlang, Elixir), where every expression returns something. Print function can print something to the standard output and besides that, it can also return some value. This is the reason why fixed assertion should also allow 2 messages, first `stream` with what goes to the standard output and the second `execute_result` with result of evaluation of this expression.

I've also made a pull request if you would like to use it: https://github.com/jupyter/jupyter_kernel_test/pull/4

**Comment by takluyver** [comment]
Closed by #4
