### ISSUE TITLE
packaging questions

### ISSUE THREAD

**Issue by kmike** [jupyter/jupyter_kernel_test#9]
Hey,

Could you please clarify some questions about packaging?
- which commit is currently uploaded to pypi?
- if pypi version doesn't have all recent fixes, is it possible to install `jupyter_kernel_version` from github? I see that it is not possible to do it with pip (as there is no setup.py in repo you can't specify a repo address and a commit and put it into requirements.txt); is it possible with flit without downloading zip file using curl/wget?

**Comment by Carreau** [comment]
> which commit is currently uploaded to pypi?

I was not even aware this was released. 

On python 3, instal `flit`, and run `flit install --symlink` from the root of the source tree.

@takluyver can you add Min and I to the owners on PyPI ?

**Comment by blink1073** [comment]
We are now using standard `setuptools`
